/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeadPublic = IDL.Record({
  'id' : IDL.Nat,
  'soldBy' : IDL.Text,
  'termsAccepted' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'amountPaid' : IDL.Text,
  'phone' : IDL.Text,
  'pendingAmount' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteLead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(LeadPublic)], ['query']),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [LeadPublic],
      [],
    ),
  'updateLeadAmountPaid' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateLeadPendingAmount' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateLeadSoldBy' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeadPublic = IDL.Record({
    'id' : IDL.Nat,
    'soldBy' : IDL.Text,
    'termsAccepted' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'amountPaid' : IDL.Text,
    'phone' : IDL.Text,
    'pendingAmount' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteLead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(LeadPublic)], ['query']),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [LeadPublic],
        [],
      ),
    'updateLeadAmountPaid' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateLeadPendingAmount' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateLeadSoldBy' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };